import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import { Navbar } from "./components/views/navbar";
import "./globals.css";
import { Footer } from "./components/views/footer";

const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({
  variable: "--font-mon",
  display:"swap",
  subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${montserrat.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
